### ISSUE TITLE
Search button submit with multiple submits

### ISSUE THREAD

**Issue by sloant** [devmatics/incoming-issues#1]
On pages with multiple submit buttons, e.g. catalog with a RiSE scrape, entering data into the catalog search box and doing a keyboard return, does not cause search in catalog. Selecting Go after entry works, just not keyboard input.

**Comment by alexdwhite** [comment]
Hi Tim, we will look at this.

**Comment by alexdwhite** [comment]
We were able to replicate it, and know what the issue is.  Difficult to explain, but basically a collision of how .NET WebForms (which iMIS RISE uses) works when it wraps the entire site in an HTML Form tag.   Basically if you hit the enter key, it will look for the default form and submission.  We are going to try to change the search textbox and button click to "block" the form submission if we can.  Its probably the best we could do.  Alternatively, we would have to modify the RISE masterpage to set the search box to "UseDefault = False".   Give us a couple days and we will get you and update.

**Comment by alexdwhite** [comment]
We added a "block submit" on the keypress down, along with what was there before on the keypress up
