### ISSUE TITLE
AIST Catalog Performance

### ISSUE THREAD

**Issue by sloant** [devmatics/incoming-issues#9]
Alex, this is from our staffer, Jake Robida. Would love your thoughts on this and if it something feasible to try to tackle. Thanks. - Tim

------------------------
**_AIST's catalog (https://imis.aist.org/store/catalog.aspx) has pretty serious performance problems - particularly when you use the Sort by feature. It takes 30+seconds to re-sort the list. My latest test was 40secs. I exported their $/ATS/Catalog/Settings/ATS_CATALOG_PRODUCTS query and they have a total of 15393 products as of right now, with big Notes values. For reference, the exported Excel file is almost 25mb! If I try to reload the catalog page then the store seems to timeout on the sebsequent load, too. I had to recycle the app pools to get the store to load for me again._**
------------------------

**Comment by alexdwhite** [comment]
Hi Tim,

So this is a situation where AIST is really pushing the use of the catalog way past the original architecture limits.
The catalog was designed to load all the products (along with their attributes and tags) into the page one time, at page load.
That way the javascript could perform the searching, sorting, and filtering. 
There seemed to be a threshold of products at around 6000 or so where we started to see the performance buckle a bit.
With AIST, they have over 15,000 products, plus gobs more attributes and tags.  In order for this to work with them properly, we would need to completely rebuild the system with a new API that handles searching via REST calls... rather than a pre-load.  It's a significant undertaking of 30+ hours.

**Comment by sloant** [comment]
Thank you. That's what we expected. I'll talk to  Randy on Monday and get his thoughts. Thoughts on multiple catalogs? We can do right now with ATS store but thinking that it would be possible to have multiple instances, so papers, books, etc.  would be their own search. Not a great solution but for a client like AIST may be best. 
Thanks again and have a great weekend!

**Comment by sloant** [comment]
@alexdwhite Some follow on thoughts. We thought maybe filtering on a topic then sorting would help performance but that doesn't appear to be the case.
A thought though is that filtering goes very quickly while sorting does not.
Any thoughts on that? 
Thanks.
Tim

**Comment by alexdwhite** [comment]
Hi Tim, the reason why that's not going to help is because it needs to be trimmed down before it even loads the page. We need to trim the payload that goes from the IMIS server to our server.

**Comment by rrichter80** [comment]
Alex,

Are the filters just controlled by css? Didn't know if you were creating a subset of the data for filtering or if you were just hiding it with css.

It makes no sense to sort the entire dataset if there are over say 500 items. But if the filter gets it down to 55 items, then it would be reasonable to sort just those 55 items. I was thinking maybe the button to sort could be turned off if there are over "X" items. But if it sorts the entire dataset BEFORE filtering, then that won't help. If it could sort the filtered dataset, then we would be good.

Thanks,
Randy

**Comment by sloant** [comment]
Alex, just wanting to check in on those. Did you see Randy's update/info earlier?
Just wanting to get something back to the client soon.
Thanks.
Tim

**Comment by sloant** [comment]
Checking to see as I thought you and Randy may have discussed more. We have open ticket with client that I want to get answered in some fashion.
Tim
